Added logout functionality
awslabs/cognito-at-edge pull request #60
Opened 2023-03-24 18:18 UTC by aszniak

*Issue # (if available):
https://github.com/awslabs/cognito-at-edge/issues/8

*Description of changes:*
Creates a behavior that allows to expire cookies and redirect to Cognito /logout endpoint. 
If there are no cookies present when trying to reach the logout endpoint, redirects to domain (app) root.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-27 12:16 UTC, jeandek commented
Hi Artur, thanks for creating this pull request. I will do my best to review it in the next couple of days.

2023-03-27 12:19 UTC, jeandek commented
Hi Artur, thanks for creating this pull request. I will do my best to review it in the next couple of days.

2023-04-24 01:39 UTC, borisfba requested changes
Hi aszniak,

First of all, thank you for your pull request. We really appreciate your contribution to our project!

I apologize for the delay in reviewing your PR. We've been swamped lately and haven't been able to keep up with our usual review timeline.

I've had a chance to review your changes and I think they look great. However, I do have a few comments and suggestions that I think would improve this feature.

2023-04-24 01:39 UTC, borisfba commented on src/index.ts
> +        return this._getRedirectResponse(tokens, cfDomain, logoutUrl, expireCookies);
When cookies are cleaned up after a user logs out, the tokens contained within them are still valid. This is especially concerning for the refresh token, which is valid for 30 days by default. I would suggest at least [revoking the refresh token](https://docs.aws.amazon.com/cognito/latest/developerguide/token-revocation.html).

2023-04-24 01:39 UTC, borisfba commented on src/index.ts
> +  _enableLogout?: boolean;
I would recommend implementing a dedicated LogoutConfiguration. If it is not defined, the logout functionality would be disabled. 

```ts
interface LogoutConfiguration {
  logoutUri: string;
  logoutRedirectUri: string;
}
```

2023-07-21 17:10 UTC, jeandek commented
Closing as this is redundant with #68 which I just merged.

2023-07-21 17:10 UTC, closed without merging